global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'data_generator'
    static_configs:
      - targets: ['data-generator:5000']
  - job_name: 'metrics_db'
    static_configs:
      - targets: ['metrics-db:5003']
